openapi: 3.1.0
info:
  title: Ryder Cup API
  description: API for managing Ryder Cup-style golf tournaments with live scoreboard support.
  version: 1.1.0
servers:
  - url: https://ryder-cup-api.onrender.com
paths:
  /admin_create_tournament:
    post:
      operationId: adminCreateTournament
      summary: Admin creates a tournament.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                start_date:
                  type: string
                end_date:
                  type: string
                format:
                  type: string
                total_rounds:
                  type: integer
      responses:
        "200":
          description: Tournament created.
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                  tournament_id:
                    type: string

  /start_tournament:
    post:
      operationId: startTournament
      summary: Organizer starts the tournament.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                tournament_id:
                  type: string
      responses:
        "200":
          description: Tournament started.
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string

  /submit_score:
    post:
      operationId: submitScore
      summary: Submit a score for a match hole.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                tournament_id:
                  type: string
                hole:
                  type: string
                player1:
                  type: string
                score1:
                  type: integer
                player2:
                  type: string
                score2:
                  type: integer
      responses:
        "200":
          description: Score submitted.
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                  winner:
                    type: string
                  match_status:
                    type: string

  /scoreboard/{tournament_id}:
    get:
      operationId: getScoreboard
      summary: Get live scoreboard for a tournament
      parameters:
        - name: tournament_id
          in: path
          required: true
          schema:
            type: string
      responses:
        "200":
          description: Live scoreboard
          content:
            application/json:
              schema:
                type: object
                properties:
                  tournament_id:
                    type: string
                  tournament_name:
                    type: string
                  status:
                    type: string
                  current_round:
                    type: integer
                  total_holes_played:
                    type: integer
                  match_status:
                    type: string
                  scoreboard:
                    type: array
                    items:
                      type: object
                      properties:
                        hole:
                          type: integer
                        scores:
                          type: object
                          additionalProperties:
                            type: integer
                        winner:
                          type: string
        "404":
          description: Tournament not found
